In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
# first i loaded the dataset
df = pd.read_csv('C:/Users/MSI KATANA/Desktop/DSGP Git Repo/DSGP-GROUP-9/newDataset.csv')
df

,Accident_Index,Local_Authority_(District),Date,Day_of_Week,Time,Year,Weather_Conditions,Urban / Rural,Speed_limit,Road_Type,Road_Surface,Pedestrian_Crossing-Physical_Facilities,Number_of_Vehicles,Light_Conditions,Junction_Detail,Junction_Control,Accident_Severity
0,200501BS00001,Kensington and Chelsea,1/4/2005,Tuesday,17:42,2005,Raining no high winds,Urban,30,Single carriageway,Wet or damp,1.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Serious
1,200501BS00002,Kensington and Chelsea,1/5/2005,Wednesday,17:36,2005,Fine no high winds,Urban,30,Dual carriageway,Dry,5.0,1,Darkness - lights lit,Crossroads,Auto traffic signal,Slight
2,200501BS00003,Kensington and Chelsea,1/6/2005,Thursday,0:15,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,2,Darkness - lights lit,Not at junction or within 20 metres,Data missing or out of range,Slight
3,200501BS00004,Kensington and Chelsea,1/7/2005,Friday,10:35,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
4,200501BS00005,Kensington and Chelsea,1/10/2005,Monday,21:13,2005,Fine no high winds,Urban,30,Single carriageway,Wet or damp,0.0,1,Darkness - lighting unknown,Not at junction or within 20 metres,Data missing or out of range,Slight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,201091NM01760,Highland,2/18/2010,Thursday,7:00,2010,Fine no high winds,Rural,60,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
1048571,201091NM01881,Highland,2/21/2010,Sunday,3:00,2010,Fine no high winds,Rural,60,Single carriageway,Frost or ice,0.0,1,Darkness - no lighting,Not at junction or within 20 metres,Data missing or out of range,Slight
1048572,201091NM01935,Highland,2/23/2010,Tuesday,9:38,2010,Fine no high winds,Rural,30,Single carriageway,Frost or ice,0.0,3,Daylight,T or staggered junction,Give way or uncontrolled,Slight
1048573,201091NM01964,Highland,2/23/2010,Tuesday,18:25,2010,Fine no high winds,Rural,60,Single carriageway,Wet or damp,0.0,2,Darkness - no lighting,T or staggered junction,Give way or uncontrolled,Serious
1048574,201091NM02142,Highland,2/28/2010,Sunday,15:45,2010,Snowing no high winds,Rural,60,Dual carriageway,Wet or damp,0.0,1,Daylight,T or staggered junction,Give way or uncontrolled,Serious

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 17 columns):
 #   Column                                   Non-Null Count    Dtype
---  ------                                   --------------    -----
 0   Accident_Index                           1048575 non-null  object
 1   Local_Authority_(District)               1048575 non-null  object
 2   Date                                     1048575 non-null  object
 3   Day_of_Week                              1048575 non-null  object
 4   Time                                     1048475 non-null  object
 5   Year                                     1048575 non-null  int64
 6   Weather_Conditions                       1048575 non-null  object
 7   Urban / Rural                            1048575 non-null  object
 8   Speed_limit                              1048575 non-null  int64
 9   Road_Type                                1048575 non-null  object
 10  Road_Surface                             1048575 non-null  object
 11  Pedestrian_Crossing-Physical_Facilities  1048538 non-null  float64
 12  Number_of_Vehicles                       1048575 non-null  int64
 13  Light_Conditions                         1048575 non-null  object
 14  Junction_Detail                          1048575 non-null  object
 15  Junction_Control                         1048575 non-null  object
 16  Accident_Severity                        1048575 non-null  object
dtypes: float64(1), int64(3), object(13)
memory usage: 136.0+ MB

In [24]:
df.shape

(1048575, 17)

In [25]:
df['Pedestrian_Crossing-Physical_Facilities'].unique()
import math

In [26]:
filter1 = df['Pedestrian_Crossing-Physical_Facilities'].apply(lambda x : not (math.isnan(x)))

In [27]:
filter2 = df.loc[filter1]
filter2

,Accident_Index,Local_Authority_(District),Date,Day_of_Week,Time,Year,Weather_Conditions,Urban / Rural,Speed_limit,Road_Type,Road_Surface,Pedestrian_Crossing-Physical_Facilities,Number_of_Vehicles,Light_Conditions,Junction_Detail,Junction_Control,Accident_Severity
0,200501BS00001,Kensington and Chelsea,1/4/2005,Tuesday,17:42,2005,Raining no high winds,Urban,30,Single carriageway,Wet or damp,1.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Serious
1,200501BS00002,Kensington and Chelsea,1/5/2005,Wednesday,17:36,2005,Fine no high winds,Urban,30,Dual carriageway,Dry,5.0,1,Darkness - lights lit,Crossroads,Auto traffic signal,Slight
2,200501BS00003,Kensington and Chelsea,1/6/2005,Thursday,0:15,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,2,Darkness - lights lit,Not at junction or within 20 metres,Data missing or out of range,Slight
3,200501BS00004,Kensington and Chelsea,1/7/2005,Friday,10:35,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
4,200501BS00005,Kensington and Chelsea,1/10/2005,Monday,21:13,2005,Fine no high winds,Urban,30,Single carriageway,Wet or damp,0.0,1,Darkness - lighting unknown,Not at junction or within 20 metres,Data missing or out of range,Slight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,201091NM01760,Highland,2/18/2010,Thursday,7:00,2010,Fine no high winds,Rural,60,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
1048571,201091NM01881,Highland,2/21/2010,Sunday,3:00,2010,Fine no high winds,Rural,60,Single carriageway,Frost or ice,0.0,1,Darkness - no lighting,Not at junction or within 20 metres,Data missing or out of range,Slight
1048572,201091NM01935,Highland,2/23/2010,Tuesday,9:38,2010,Fine no high winds,Rural,30,Single carriageway,Frost or ice,0.0,3,Daylight,T or staggered junction,Give way or uncontrolled,Slight
1048573,201091NM01964,Highland,2/23/2010,Tuesday,18:25,2010,Fine no high winds,Rural,60,Single carriageway,Wet or damp,0.0,2,Darkness - no lighting,T or staggered junction,Give way or uncontrolled,Serious
1048574,201091NM02142,Highland,2/28/2010,Sunday,15:45,2010,Snowing no high winds,Rural,60,Dual carriageway,Wet or damp,0.0,1,Daylight,T or staggered junction,Give way or uncontrolled,Serious

In [28]:
filter2.shape

(1048538, 17)

In [31]:
df = filter2

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1048538 entries, 0 to 1048574
Data columns (total 17 columns):
 #   Column                                   Non-Null Count    Dtype
---  ------                                   --------------    -----
 0   Accident_Index                           1048538 non-null  object
 1   Local_Authority_(District)               1048538 non-null  object
 2   Date                                     1048538 non-null  object
 3   Day_of_Week                              1048538 non-null  object
 4   Time                                     1048439 non-null  object
 5   Year                                     1048538 non-null  int64
 6   Weather_Conditions                       1048538 non-null  object
 7   Urban / Rural                            1048538 non-null  object
 8   Speed_limit                              1048538 non-null  int64
 9   Road_Type                                1048538 non-null  object
 10  Road_Surface                             1048538 non-null  object
 11  Pedestrian_Crossing-Physical_Facilities  1048538 non-null  float64
 12  Number_of_Vehicles                       1048538 non-null  int64
 13  Light_Conditions                         1048538 non-null  object
 14  Junction_Detail                          1048538 non-null  object
 15  Junction_Control                         1048538 non-null  object
 16  Accident_Severity                        1048538 non-null  object
dtypes: float64(1), int64(3), object(13)
memory usage: 144.0+ MB

In [33]:
df

,Accident_Index,Local_Authority_(District),Date,Day_of_Week,Time,Year,Weather_Conditions,Urban / Rural,Speed_limit,Road_Type,Road_Surface,Pedestrian_Crossing-Physical_Facilities,Number_of_Vehicles,Light_Conditions,Junction_Detail,Junction_Control,Accident_Severity
0,200501BS00001,Kensington and Chelsea,1/4/2005,Tuesday,17:42,2005,Raining no high winds,Urban,30,Single carriageway,Wet or damp,1.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Serious
1,200501BS00002,Kensington and Chelsea,1/5/2005,Wednesday,17:36,2005,Fine no high winds,Urban,30,Dual carriageway,Dry,5.0,1,Darkness - lights lit,Crossroads,Auto traffic signal,Slight
2,200501BS00003,Kensington and Chelsea,1/6/2005,Thursday,0:15,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,2,Darkness - lights lit,Not at junction or within 20 metres,Data missing or out of range,Slight
3,200501BS00004,Kensington and Chelsea,1/7/2005,Friday,10:35,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
4,200501BS00005,Kensington and Chelsea,1/10/2005,Monday,21:13,2005,Fine no high winds,Urban,30,Single carriageway,Wet or damp,0.0,1,Darkness - lighting unknown,Not at junction or within 20 metres,Data missing or out of range,Slight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,201091NM01760,Highland,2/18/2010,Thursday,7:00,2010,Fine no high winds,Rural,60,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
1048571,201091NM01881,Highland,2/21/2010,Sunday,3:00,2010,Fine no high winds,Rural,60,Single carriageway,Frost or ice,0.0,1,Darkness - no lighting,Not at junction or within 20 metres,Data missing or out of range,Slight
1048572,201091NM01935,Highland,2/23/2010,Tuesday,9:38,2010,Fine no high winds,Rural,30,Single carriageway,Frost or ice,0.0,3,Daylight,T or staggered junction,Give way or uncontrolled,Slight
1048573,201091NM01964,Highland,2/23/2010,Tuesday,18:25,2010,Fine no high winds,Rural,60,Single carriageway,Wet or damp,0.0,2,Darkness - no lighting,T or staggered junction,Give way or uncontrolled,Serious
1048574,201091NM02142,Highland,2/28/2010,Sunday,15:45,2010,Snowing no high winds,Rural,60,Dual carriageway,Wet or damp,0.0,1,Daylight,T or staggered junction,Give way or uncontrolled,Serious

In [34]:
df.to_csv("edit1Newdataset.csv")

In [40]:
df['Day_of_Week'].value_counts()

Day_of_Week
Friday       171905
Wednesday    157982
Tuesday      156116
Thursday     155783
Monday       148499
Saturday     142223
Sunday       116030
Name: count, dtype: int64

In [41]:
# first i loaded the dataset
df1 = pd.read_csv('C:/Users/MSI KATANA/Desktop/DSGP Git Repo/DSGP-GROUP-9/edit1Newdataset.csv')
df1

,Unnamed: 0,Accident_Index,Local_Authority_(District),Date,Day_of_Week,Time,Year,Weather_Conditions,Urban / Rural,Speed_limit,Road_Type,Road_Surface,Pedestrian_Crossing-Physical_Facilities,Number_of_Vehicles,Light_Conditions,Junction_Detail,Junction_Control,Accident_Severity
0,0,200501BS00001,Kensington and Chelsea,1/4/2005,Tuesday,17:42,2005,Raining no high winds,Urban,30,Single carriageway,Wet or damp,1.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Serious
1,1,200501BS00002,Kensington and Chelsea,1/5/2005,Wednesday,17:36,2005,Fine no high winds,Urban,30,Dual carriageway,Dry,5.0,1,Darkness - lights lit,Crossroads,Auto traffic signal,Slight
2,2,200501BS00003,Kensington and Chelsea,1/6/2005,Thursday,0:15,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,2,Darkness - lights lit,Not at junction or within 20 metres,Data missing or out of range,Slight
3,3,200501BS00004,Kensington and Chelsea,1/7/2005,Friday,10:35,2005,Fine no high winds,Urban,30,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
4,4,200501BS00005,Kensington and Chelsea,1/10/2005,Monday,21:13,2005,Fine no high winds,Urban,30,Single carriageway,Wet or damp,0.0,1,Darkness - lighting unknown,Not at junction or within 20 metres,Data missing or out of range,Slight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048533,1048570,201091NM01760,Highland,2/18/2010,Thursday,7:00,2010,Fine no high winds,Rural,60,Single carriageway,Dry,0.0,1,Daylight,Not at junction or within 20 metres,Data missing or out of range,Slight
1048534,1048571,201091NM01881,Highland,2/21/2010,Sunday,3:00,2010,Fine no high winds,Rural,60,Single carriageway,Frost or ice,0.0,1,Darkness - no lighting,Not at junction or within 20 metres,Data missing or out of range,Slight
1048535,1048572,201091NM01935,Highland,2/23/2010,Tuesday,9:38,2010,Fine no high winds,Rural,30,Single carriageway,Frost or ice,0.0,3,Daylight,T or staggered junction,Give way or uncontrolled,Slight
1048536,1048573,201091NM01964,Highland,2/23/2010,Tuesday,18:25,2010,Fine no high winds,Rural,60,Single carriageway,Wet or damp,0.0,2,Darkness - no lighting,T or staggered junction,Give way or uncontrolled,Serious
1048537,1048574,201091NM02142,Highland,2/28/2010,Sunday,15:45,2010,Snowing no high winds,Rural,60,Dual carriageway,Wet or damp,0.0,1,Daylight,T or staggered junction,Give way or uncontrolled,Serious

In [42]:
# main selected fields
selected_columns = ['Accident_Index', 'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)'] 
df_selected = df1[selected_columns]
df_selected

,Accident_Index,Date,Day_of_Week,Time,Local_Authority_(District)
0,200501BS00001,1/4/2005,Tuesday,17:42,Kensington and Chelsea
1,200501BS00002,1/5/2005,Wednesday,17:36,Kensington and Chelsea
2,200501BS00003,1/6/2005,Thursday,0:15,Kensington and Chelsea
3,200501BS00004,1/7/2005,Friday,10:35,Kensington and Chelsea
4,200501BS00005,1/10/2005,Monday,21:13,Kensington and Chelsea
...,...,...,...,...,...
1048533,201091NM01760,2/18/2010,Thursday,7:00,Highland
1048534,201091NM01881,2/21/2010,Sunday,3:00,Highland
1048535,201091NM01935,2/23/2010,Tuesday,9:38,Highland
1048536,201091NM01964,2/23/2010,Tuesday,18:25,Highland
1048537,201091NM02142,2/28/2010,Sunday,15:45,Highland

In [44]:
# Checking  missing values in the DataFrame
missing_values_in_data_frame = df_selected.isnull()

# number of missing values in each column
missing_values_count_in_data_frame = df_selected.isnull().sum()

# print the result
print("Missing Values in Each Column:")
print(missing_values_count_in_data_frame)

Missing Values in Each Column:
Accident_Index                 0
Date                           0
Day_of_Week                    0
Time                          99
Local_Authority_(District)     0
dtype: int64

In [46]:
# drop the rows with any missing values
df_selected = df_selected.dropna()
df_selected

,Accident_Index,Date,Day_of_Week,Time,Local_Authority_(District)
0,200501BS00001,1/4/2005,Tuesday,17:42,Kensington and Chelsea
1,200501BS00002,1/5/2005,Wednesday,17:36,Kensington and Chelsea
2,200501BS00003,1/6/2005,Thursday,0:15,Kensington and Chelsea
3,200501BS00004,1/7/2005,Friday,10:35,Kensington and Chelsea
4,200501BS00005,1/10/2005,Monday,21:13,Kensington and Chelsea
...,...,...,...,...,...
1048533,201091NM01760,2/18/2010,Thursday,7:00,Highland
1048534,201091NM01881,2/21/2010,Sunday,3:00,Highland
1048535,201091NM01935,2/23/2010,Tuesday,9:38,Highland
1048536,201091NM01964,2/23/2010,Tuesday,18:25,Highland
1048537,201091NM02142,2/28/2010,Sunday,15:45,Highland

In [47]:
# remove the duplicate values in rows 
df_selected = df_selected.drop_duplicates()
df_selected

,Accident_Index,Date,Day_of_Week,Time,Local_Authority_(District)
0,200501BS00001,1/4/2005,Tuesday,17:42,Kensington and Chelsea
1,200501BS00002,1/5/2005,Wednesday,17:36,Kensington and Chelsea
2,200501BS00003,1/6/2005,Thursday,0:15,Kensington and Chelsea
3,200501BS00004,1/7/2005,Friday,10:35,Kensington and Chelsea
4,200501BS00005,1/10/2005,Monday,21:13,Kensington and Chelsea
...,...,...,...,...,...
1048533,201091NM01760,2/18/2010,Thursday,7:00,Highland
1048534,201091NM01881,2/21/2010,Sunday,3:00,Highland
1048535,201091NM01935,2/23/2010,Tuesday,9:38,Highland
1048536,201091NM01964,2/23/2010,Tuesday,18:25,Highland
1048537,201091NM02142,2/28/2010,Sunday,15:45,Highland

In [48]:
# Checking  missing values in the DataFrame
missing_values_in_data_frame = df_selected.isnull()

# number of missing values in each column
missing_values_count_in_data_frame = df_selected.isnull().sum()

# print the result
print("Missing Values in Each Column:")
print(missing_values_count_in_data_frame)

Missing Values in Each Column:
Accident_Index                0
Date                          0
Day_of_Week                   0
Time                          0
Local_Authority_(District)    0
dtype: int64

In [49]:
# confirmd no missing values

In [57]:
# Assuming your original DataFrame is named 'df_selected'
# Specify the correct date format using the 'format' parameter and 'dayfirst=True'
df_selected['Year'] = pd.to_datetime(df_selected['Date'], format='%m/%d/%Y', dayfirst=True).dt.year

# Map day of the week numbers to day names
day_mapping = {1: 'Monday', 2: 'Tuesday', 3: 'Wednesday', 4: 'Thursday', 5: 'Friday', 6: 'Saturday', 7: 'Sunday'}
df_selected['Day_of_the_Week'] = pd.to_datetime(df_selected['Date'], format='%m/%d/%Y', dayfirst=True).dt.dayofweek.map(day_mapping)

# Create a new column for time periods (1 to 24)
df_selected['Time_Period'] = pd.to_datetime(df_selected['Time']).dt.hour + 1

# Create a new DataFrame with the desired format
result_df = df_selected.groupby(['Local_Authority_(District)', 'Year', 'Day_of_the_Week', 'Time_Period'])['Accident_Index'].count().reset_index()
result_df.rename(columns={'Accident_Index': 'Acc. Count'}, inplace=True)

# Print the first few rows of the result DataFrame
print(result_df.head(1000))

C:\Users\MSI KATANA\AppData\Local\Temp\ipykernel_11968\133000641.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Year'] = pd.to_datetime(df_selected['Date'], format='%m/%d/%Y', dayfirst=True).dt.year
C:\Users\MSI KATANA\AppData\Local\Temp\ipykernel_11968\133000641.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Day_of_the_Week'] = pd.to_datetime(df_selected['Date'], format='%m/%d/%Y', dayfirst=True).dt.dayofweek.map(day_mapping)
C:\Users\MSI KATANA\AppData\Local\Temp\ipykernel_11968\133000641.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_selected['Time_Period'] = pd.to_datetime(df_selected['Time']).dt.hour + 1
C:\Users\MSI KATANA\AppData\Local\Temp\ipykernel_11968\133000641.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Time_Period'] = pd.to_datetime(df_selected['Time']).dt.hour + 1

    Local_Authority_(District)  Year Day_of_the_Week  Time_Period  Acc. Count
0                Aberdeen City  2005          Friday            1           5
1                Aberdeen City  2005          Friday            2           2
2                Aberdeen City  2005          Friday            3           1
3                Aberdeen City  2005          Friday            4           2
4                Aberdeen City  2005          Friday            5           1
..                         ...   ...             ...          ...         ...
995              Aberdeenshire  2008          Monday           21           4
996              Aberdeenshire  2008          Monday           22           3
997              Aberdeenshire  2008          Monday           23           2
998              Aberdeenshire  2008          Monday           24           2
999              Aberdeenshire  2008        Saturday            1           2

[1000 rows x 5 columns]

In [58]:
result_df

,Local_Authority_(District),Year,Day_of_the_Week,Time_Period,Acc. Count
0,Aberdeen City,2005,Friday,1,5
1,Aberdeen City,2005,Friday,2,2
2,Aberdeen City,2005,Friday,3,1
3,Aberdeen City,2005,Friday,4,2
4,Aberdeen City,2005,Friday,5,1
...,...,...,...,...,...
249426,York,2010,Wednesday,19,8
249427,York,2010,Wednesday,20,3
249428,York,2010,Wednesday,21,2
249429,York,2010,Wednesday,22,1
249430,York,2010,Wednesday,24,1